- name: Jenkins Setup
  ansible.builtin.include_tasks:
    file: jenkins-setup.yaml
  when: jenkins-setup | bool

- name: Jenkins Jobs
  ansible.builtin.include_tasks:
    file: jenkins-jobs.yaml
  when: jenkins-jobs | bool




